name: Build & Push Unbound

on:
  push:
    branches: [ main ]
    paths:
      - 'unbound/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *'  # daily rebuild to pick up security updates

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1) Build a LOCAL test image for the runner arch and load it into the Docker daemon
      - name: Build (local test image)
        uses: docker/build-push-action@v6
        with:
          context: ./unbound
          build-args: |
            BASE=debian:bookworm-slim
          load: true
          push: false
          platforms: linux/amd64
          tags: unbound:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2) Smoke test: start unbound and verify we can resolve something
      - name: Smoke test container
        shell: bash
        run: |
          set -euo pipefail
          docker rm -f unboundtest >/dev/null 2>&1 || true
          docker run -d --name unboundtest unbound:test

          # Wait up to ~60s for readiness by probing with dig inside the container
          for i in {1..30}; do
            if docker exec unboundtest sh -lc 'dig @127.0.0.1 -p 5335 cloudflare.com A +timeout=2 +tries=1 +short' | grep -Eq '^[0-9]+\.'; then
              echo "DNS OK"
              break
            fi
            sleep 2
            if [ "$i" -eq 30 ]; then
              echo "Unbound did not answer in time"; docker logs unboundtest || true; exit 1
            fi
          done

          docker rm -f unboundtest

      # 3) If the smoke test passed, do the real multi-arch build & push
      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./unbound
          build-args: |
            BASE=debian:bookworm-slim
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/unbound:latest
            ghcr.io/${{ github.repository_owner }}/unbound:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
