name: Build & Push Unbound

on:
  push:
    branches: [ main ]
    paths:
      - "unbound/**"
      - ".github/workflows/build.yml"
  schedule:
    - cron: "0 8 * * *"  # daily at 08:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./unbound
          push: true
          pull: true        # always refresh base layers
          tags: |
            ghcr.io/${{ github.repository_owner }}/unbound:latest
            ghcr.io/${{ github.repository_owner }}/unbound:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
