name: Build & Push Unbound

on:
  push:
    branches: [ main ]
    paths:
      - 'unbound/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *'  # daily rebuild to pick up security updates

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: false
    env:
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: "plain"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker info (debug)
        run: |
          docker version
          docker info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- Build a LOCAL test image (runner arch) and load it ----
      - name: Build (local test image)
        uses: docker/build-push-action@v6
        with:
          context: ./unbound
          build-args: |
            BASE=debian:bookworm-slim
          load: true
          push: false
          platforms: linux/amd64
          tags: unbound:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- Smoke test: start unbound and verify DNS works ----
      - name: Smoke test container
        shell: bash
        run: |
          set -euo pipefail
          docker rm -f unboundtest >/dev/null 2>&1 || true
          docker run -d --name unboundtest unbound:test

          echo "===> Container logs (initial)"
          sleep 2
          docker logs unboundtest || true

          echo "===> Wait up to 90s for DNS to respond"
          for i in {1..45}; do
            if docker exec unboundtest sh -lc 'dig @127.0.0.1 -p 5335 cloudflare.com A +timeout=2 +tries=1 +short' | grep -Eq '^[0-9]+\.'; then
              echo "DNS OK"
              break
            fi
            sleep 2
            if [ "$i" -eq 45 ]; then
              echo "Unbound did not answer in time"
              echo "===> Final container logs"
              docker logs unboundtest || true
              echo "===> Print config for debugging"
              docker exec unboundtest sh -lc 'unbound -V || true; echo; cat /etc/unbound/unbound.conf || true'
              exit 1
            fi
          done

          docker rm -f unboundtest

      # ---- Multi-arch build & push (only if smoke test passed) ----
      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./unbound
          build-args: |
            BASE=debian:bookworm-slim
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/unbound:latest
            ghcr.io/${{ github.repository_owner }}/unbound:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show pushed tags (debug)
        if: always()
        run: |
          echo "Pushed: ghcr.io/${{ github.repository_owner }}/unbound:latest"
          echo "Pushed: ghcr.io/${{ github.repository_owner }}/unbound:${{ github.sha }}"
